# Makefile - Simple java makefile

# Define java compiler and flags and how to compile .java files to .class files
JFLAGS = -g
#JFLAGS = -g:none
JC = javac
.SUFFIXES: .java .class
.java.class:
	$(JC) $(JFLAGS) $*.java

# Define delete command
RM = rm -f

# A list of the relevant java sources to be compiled
CLASSES = \
    HelloWorld.java \

# Default make target
default: classes

# Defines classes target to compile files in CLASSES
classes: $(CLASSES:.java=.class)

# Cleanup files generated by compiler
clean:
	$(RM) *.class
